# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stubs_service_B/proto_service_B/catalogo_autores.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stubs_service_B/proto_service_B/catalogo_autores.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6stubs_service_B/proto_service_B/catalogo_autores.proto\x12\x10\x63\x61talogo_autores\" \n\x0c\x41utorRequest\x12\x10\n\x08livro_id\x18\x01 \x01(\t\"i\n\rAutorResponse\x12\x12\n\nnome_autor\x18\x01 \x01(\t\x12\x13\n\x0bidade_autor\x18\x02 \x01(\x05\x12\x15\n\rnacionalidade\x18\x03 \x01(\t\x12\x18\n\x10obras_conhecidas\x18\x04 \x03(\t2`\n\x0c\x41utorService\x12P\n\rGetInfosAutor\x12\x1e.catalogo_autores.AutorRequest\x1a\x1f.catalogo_autores.AutorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stubs_service_B.proto_service_B.catalogo_autores_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTORREQUEST']._serialized_start=76
  _globals['_AUTORREQUEST']._serialized_end=108
  _globals['_AUTORRESPONSE']._serialized_start=110
  _globals['_AUTORRESPONSE']._serialized_end=215
  _globals['_AUTORSERVICE']._serialized_start=217
  _globals['_AUTORSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
